version: '3.6'
services:
  postgres:
    environment:
      POSTGRES_PASSWORD: postgrespassword
    image: postgres:12
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v2.1.1.cli-migrations-v2
    depends_on:
      - postgres
    environment:
      FETCH_GEAR_DATA: ${DOCKER_GATEWAY_HOST:-host.docker.internal}:8888/.netlify/functions/fetch-gear-data
      FETCH_SEGMENT_DATA: ${DOCKER_GATEWAY_HOST:-host.docker.internal}:8888/.netlify/functions/fetch-segment-data
      FETCH_WEATHER_DATA_ACTIVITY: ${DOCKER_GATEWAY_HOST:-host.docker.internal}:8888/.netlify/functions/fetch-weather-data-activity
      FETCH_WEATHER_DATA_SEGMENT: ${DOCKER_GATEWAY_HOST:-host.docker.internal}:8888/.netlify/functions/fetch-weather-data-segment
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLED_LOG_TYPES:
        startup, http-log, webhook-log, websocket-log,
        query-log
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: user
    ports:
      - 8080:8080
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    restart: always
volumes:
  db_data: null
