version: 2
admin_secret: myadminsecretkey
endpoint: http://localhost:8080
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://172.17.0.1:8888/.netlify/functions/
