- hosts: localhost
  tasks:
    - name: PGDump from StravaDB everything
      command: docker exec strava-personal-leaderboard_postgres_1 sh -c "pg_dump -U postgres postgres > db.sql"
      tags:
        - db
    - name: PGDump from StravaDB data only
      command: docker exec strava-personal-leaderboard_postgres_1 sh -c "pg_dump -U postgres -d postgres --data-only --schema public > db.sql"
      tags:
        - data

    - name: copy the file from docker
      command: docker cp strava-personal-leaderboard_postgres_1:/db.sql ../\$(date +"%Y-%m-%d")-db.sql
      tags:
        - always
